service: margarita-graphql

provider:
  name: aws
  runtime: nodejs8.10
  stage: staging
  region: eu-central-1
functions:
  margarita-graphql:
    handler: lambda/dist/index.handler
    environmentVariables:
      BASE_URL: ${env:BASE_URL}
      API_KEY: ${env:API_KEY}
    events:
      - http:
          path: /graphql
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Client
            allowCredentials: false
      - http:
          path: /graphql
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Client
            allowCredentials: false
