// @flow

import { type StylePropType } from '@kiwicom/universal-components';

export type IllustrationNameType =
  | 'Accommodation'
  | 'AirHelp'
  | 'AirportTransport'
  | 'AirportTransportTaxi'
  | 'AirportShuttle'
  | 'BaggageDrop'
  | 'Boarding'
  | 'BoardingPass'
  | 'BusinessTravel'
  | 'CabinBaggage'
  | 'DesktopSearch'
  | 'EnjoyApp'
  | 'Error'
  | 'FastTrack'
  | 'Feedback'
  | 'Help'
  | 'Improve'
  | 'Insurance'
  | 'InviteAFriend'
  | 'Login'
  | 'Lounge'
  | 'Mailbox'
  | 'Meal'
  | 'MobileApp'
  | 'Money'
  | 'MusicalInstruments'
  | 'NetVerify'
  | 'NoBookings'
  | 'NoFavoriteFlights'
  | 'Nomad'
  | 'NoNotification'
  | 'NoResults'
  | 'Offline'
  | 'OnlineCheckIn'
  | 'OpenSearch'
  | 'Parking'
  | 'Pets'
  | 'PlaceholderAirport'
  | 'PlaceholderDestination'
  | 'PlaceholderHotel'
  | 'PlaceholderTours'
  | 'PlaneAndMoney'
  | 'PriorityBoarding'
  | 'Rating'
  | 'ReferAFriend'
  | 'RentalCar'
  | 'Seating'
  | 'SpecialAssistance'
  | 'SportsEquipment'
  | 'Success'
  | 'Time'
  | 'TimelineBoarding'
  | 'TimelineDropBaggage'
  | 'TimelineLeave'
  | 'TimelinePick'
  | 'Tours'
  | 'Train'
  | 'TransportBus'
  | 'TransportTaxi';

export type IllustrationProps = {|
  name: IllustrationNameType,
  style?: StylePropType,
|};
