# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/margarita
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test-ci

  build-and-deploy-graphql:
    docker:
      - image: circleci/node:10
    working_directory: ~/margarita
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build GraphQL lambda
          command: yarn build:graphql
      - run:
          name: Deploy GraphQL lambda
          command: yarn deploy:graphql

workflows:
  version: 2
  test-and-release:
    jobs:
      - test
      - build-and-deploy-graphql:
          filters:
            branches:
              only: master
