# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/margarita
  docker:
    - image: circleci/node:10

version: 2
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/margarita
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths: .
  build-universal-components:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/margarita
      - run: yarn workspace @kiwicom/universal-components build
      - persist_to_workspace:
          root: .
          paths: .
  flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/margarita
      - run: yarn flow
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/margarita
      - run: yarn lint
  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/margarita
      - restore_cache:
          keys:
            - v1-0-jest-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-0-jest-cache-
      - run: yarn test --ci --color --maxWorkers=2
      - save_cache:
          key: v1-0-jest-cache-{{ checksum "package.json" }}
          paths:
            - .jestCache
      - persist_to_workspace:
          root: .
          paths: .

  build-and-deploy-landing-page:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "56:b8:5a:30:ca:27:22:43:2d:9a:9e:42:4b:e6:a1:9a"
      - run:
          name: Configure Git User
          command: |
            git config user.email "me@robincussol.com"
            git config user.name "GH Pages Bot"
      - run:
          name: Deploy landing page
          command: yarn landing-page:deploy

  build-and-deploy-graphql:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build GraphQL lambda
          command: yarn graphql:build
      - run:
          name: Deploy GraphQL lambda
          command: yarn graphql:deploy

workflows:
  version: 2
  test-and-release:
    jobs:
      - install-dependencies
      - build-universal-components:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
            - build-universal-components
      - flow:
          requires:
            - install-dependencies
            - build-universal-components
      - unit-tests:
          requires:
            - install-dependencies
            - build-universal-components
      - build-and-deploy-graphql:
          requires:
            - lint
            - unit-tests
          filters:
            branches:
              only: master
      - build-and-deploy-landing-page:
          requires:
            - lint
            - unit-tests
          filters:
            branches:
              only: master
